### PR TITLE
Implement naive meta tag support

### PR DESCRIPTION
**Pull request by jpadilla**
After hearing about Dockyard's new site using fastboot, we wanted to take it out for a spin on a new project. We noticed it wasn't yet possible to set meta tags like `description`. This allows setting meta tags similar to how we can set the document's title.

```javascript
Ember.set(renderer, '_dom.document.title', 'Application Route -- Title');
Ember.set(renderer, 'metaTags', [{
  name: 'description',
  content: 'something here'
}, {
  property: 'og:image',
  content: 'http://placehold.it/500x500'
}]);
```

This obviously still feels hacky but seems to work just fine so we decided to share and hopefully get some feedback.

Update: With a few simple tweaks this and #23 can play nicely together.

### CODE REVIEW

**Comment by gdub22** [comment]
@jpadilla  :heart: Looks great.  Some ideas for additional support:

- Supporting metadata with other tags such as `link` (canonical, author, etc).
- Exposing the api so the Ember router can keep things in sync during clien-side transitions.

**Comment by gcollazo** [comment]
@gdub22 :+1: for supporting supporting `<link>` tags.

What is the use case for updating `<meta>` or `<link>` tags while the app is running in the browser? I believe those are only important when the page is requested by a crawler in which case fastboot would do the right thing.

**Comment by gdub22** [comment]
@gcollazo you are right about the crawler, it would just be nice to keep them in sync.  Thinking about it more, it would be good to have this as an addon where you could define meta for each route. (https://github.com/ronco/ember-cli-meta-tags is a start) and fastboot just provides an injection point.  Kinda how the title works now with https://github.com/kimroen/ember-cli-document-title

**Comment by ronco** [comment]
This is great idea.  I'd love to see it support arbitrary head content.

**Comment by jasonmit** [comment]
> This is great idea. I'd love to see it support arbitrary head content.

I second this.  I'll need to be able to inject additional scripts into the head dynamically and would love for this to be generic enough to support all head content.

**Comment by rwjblue** [comment]
I would prefer tweaking [simple-dom here](https://github.com/krisselden/simple-dom/blob/master/lib/simple-dom/document.js#L11) to add:

```javascript
this.head = new Element('head');
```

Then we can handle arbitrary head content here....

**Comment by jpadilla** [comment]
@rwjblue btw this is ready for another look whenever you get the chance.

**Comment by jpadilla** [comment]
Tests are currently not passing, since we'd need https://github.com/krisselden/simple-dom/pull/12 to be merged.

**Comment by gdub22** [comment]
@jpadilla :+1: I'd say that the head addition by itself is enough, then let the developer/addons implement the meta tags/arbitrary head content.  I have this [addon](https://github.com/gdub22/ember-document-meta) just about working with your additions here and in simple dom.

**Comment by jasonmit** [comment]
@jpadilla Any progress?  I can help out if it's a time thing.

**Comment by jpadilla** [comment]
@jasonmit feel free to pick up. There's probably just a few things left after the simple-dom update.

**Comment by esistgut** [comment]
Are there updates on this?

**Comment by ronco** [comment]
@esistgut I was actually planning on taking a crack at finishing it up this evening.

**Comment by tomdale** [comment]
Closed in favor of #114

**Pull request closed without merging**
