### PR TITLE
Add isFastboot property to service

### PR DESCRIPTION
**Pull request by davidpett**
A convenience property to allow users to check if it is in fastboot mode or not

### CODE REVIEW

**Comment by tomdale** [comment]
Should be `isFastBoot`

**Comment by rwjblue** [comment]
> Should be isFastBoot

We should have a "Annoying Capitalization Details" section in the README. :smiling_imp:

**Comment by davidpett** [comment]
Changed it to be proper, good sir.

**Comment by tomdale** [comment]
@davidpett So looking at this more closely, I think better check is not `window` or `document` but to see if the `FastBoot` global exists. Sorry I didn't see that earlier!

**Comment by davidpett** [comment]
Ahh, didn't realize that was a thing. Not sure how to create a test for this, but I did test it in my app and it works as advertised. EVERYBODY GETS A FASTBOOT!

**Pull request merged**
