### PR TITLE
Better failure detection

### PR DESCRIPTION
**Pull request by tomdale**
This commit wraps each file that gets put in `vendor` in a `try/catch`. This allows us to capture FastBoot-incompatible addons and print a much more useful error message in the console.

Note that this relies on monkeypatching Ember CLI's `EmberApp` method in a very hacky way. @stefanpenner thinks it may be appropriate to expose a hook that we can use instead.

### CODE REVIEW

**Comment by rwjblue** [comment]
Doesn't this break source maps?

**Comment by rwjblue** [comment]
I am also wondering about performance. It is my understanding that using a try catch in some cases prevent V8 from optimizing. Is that an issue here?

**Comment by stefanpenner** [comment]
> Doesn't this break source maps?

Yes it will, we will have to come up with a better strategy at some point. That being said, if this is only for fast-boot builds it may be ok for awhile?

**Comment by stefanpenner** [comment]
@rwjblue it would prevent the context from being optimized, but not nested contexts. I am unsure as to the magnitude of the issue.

There is an alternative way for us to do this without try/catch, if it turns out to be a measurable issue.

```
function checkDeps() {
setTimeout(function() { /* check which deps have run and which haven't figuring out what went sideways */ });
}

startScript('jQuery');
//..
endScript('jQuery');

```

**Comment by tomdale** [comment]
I think https://github.com/ember-fastboot/ember-fastboot-server/pull/16 is a better solution to this. Let's revisit if this remains a problem for people.

**Pull request closed without merging**
